version: "3.8"

services:
  mongo:
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: development.password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./cert:/cert
    command: redis-server --requirepass "development.password" --tls-port 6379 --port 0 --tls-cert-file /cert/redis-server-cert.pem --tls-key-file /cert/redis-server-key.pem --tls-ca-cert-file /cert/ca-cert.pem