name: Main Workflow
on:
  - push
  - pull_request
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set up vendor
        run: go mod vendor
      - name: Test
        run: sh ./test.sh
      - name: Build
        run: sh ./build.sh